import type { ActivityEvent } from "@/types";

export const DEMO_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-001",
    type: "invoice_submitted",
    actorId: "user-daniel",
    actorName: "Daniel",
    actorRole: "CHILD",
    description: "Daniel submitted an invoice for Clean Your Room",
    jobTitle: "Clean Your Room",
    createdAt: "2026-04-25T14:30:00Z",
  },
  {
    id: "act-002",
    type: "proposal_submitted",
    actorId: "user-daniel",
    actorName: "Daniel",
    actorRole: "CHILD",
    description: "Daniel proposed a new job: Deep Clean the Bathroom",
    jobTitle: "Deep Clean the Bathroom",
    createdAt: "2026-04-25T16:00:00Z",
  },
  {
    id: "act-003",
    type: "trusted_adult_proposed",
    actorId: "user-joe",
    actorName: "Grandpa Joe",
    actorRole: "TRUSTED_ADULT",
    description: "Grandpa Joe posted a new job for the kids",
    jobTitle: "Organize the Pantry Shelf",
    createdAt: "2026-04-25T11:00:00Z",
  },
  {
    id: "act-004",
    type: "job_claimed",
    actorId: "user-mateo",
    actorName: "Mateo",
    actorRole: "CHILD",
    description: "Mateo claimed: Take Out Trash for the Week",
    jobTitle: "Take Out Trash for the Week",
    createdAt: "2026-04-22T08:30:00Z",
  },
  {
    id: "act-005",
    type: "invoice_approved",
    actorId: "user-santiago",
    actorName: "Santiago",
    actorRole: "PARENT",
    description: "Invoice approved for: Read to Your Younger Brother (+5 bonus tokens!)",
    jobTitle: "Read to Your Younger Brother",
    createdAt: "2026-04-19T18:00:00Z",
  },
  {
    id: "act-006",
    type: "reward_redeemed",
    actorId: "user-daniel",
    actorName: "Daniel",
    actorRole: "CHILD",
    description: "Daniel redeemed Movie Night (50 tokens)",
    createdAt: "2026-04-10T18:00:00Z",
  },
  {
    id: "act-007",
    type: "job_posted",
    actorId: "user-santiago",
    actorName: "Santiago",
    actorRole: "PARENT",
    description: "New job posted: Create a Lemonade Stand Budget",
    jobTitle: "Create a Lemonade Stand Budget",
    createdAt: "2026-04-24T09:00:00Z",
  },
  {
    id: "act-008",
    type: "reward_redeemed",
    actorId: "user-mateo",
    actorName: "Mateo",
    actorRole: "CHILD",
    description: "Mateo redeemed Extra Dessert (30 tokens)",
    createdAt: "2026-04-22T19:00:00Z",
  },
];
