import type { FamilyEconomySettings, PraiseBankItem, JobSuggestion } from "@/types";

export const DEMO_ECONOMY_SETTINGS: FamilyEconomySettings = {
  familyId: "family-reyes",
  currencyType: "VIRTUAL_TOKENS",
  tokenName: "tokens",
  requireApprovalForPayouts: true,
  allowChildProposals: true,
  allowTrustedAdultJobs: true,
  defaultProofRequirement: "AFTER_ONLY",
  requireReflection: true,
  enableBonuses: true,
  enableSavingsGoals: true,
  enableSkillBadges: true,
  enableWeeklyReports: true,
  trustedAdultJobsRequireApproval: true,
};

export const DEMO_PRAISE_BANK: PraiseBankItem[] = [
  { id: "praise-1", text: "You showed initiative.", category: "Initiative" },
  { id: "praise-2", text: "You followed through.", category: "Follow-through" },
  { id: "praise-3", text: "You did hard work without complaining.", category: "Diligence" },
  { id: "praise-4", text: "You helped our family.", category: "Service" },
  { id: "praise-5", text: "You improved after feedback.", category: "Resilience" },
  { id: "praise-6", text: "You should be proud of this.", category: "General" },
  { id: "praise-7", text: "You showed responsibility.", category: "Responsibility" },
  { id: "praise-8", text: "You handled correction well.", category: "Resilience" },
  { id: "praise-9", text: "You went above and beyond.", category: "Excellence" },
  { id: "praise-10", text: "You did careful work.", category: "Quality" },
];

export const DEMO_JOB_SUGGESTIONS: JobSuggestion[] = [
  // Ages 5-7
  {
    id: "sugg-001",
    ageRange: "5-7",
    title: "Put Toys Away",
    description: "Pick up all toys from the floor and put them in their bins.",
    category: "ORGANIZATION",
    difficulty: "EASY",
    virtueFocus: ["RESPONSIBILITY"],
    suggestedReward: { min: 5, max: 10 },
    suggestedChecklist: ["Pick up all floor toys", "Put toys in correct bin", "Push bins back into place"],
  },
  {
    id: "sugg-002",
    ageRange: "5-7",
    title: "Feed the Pets",
    description: "Fill the food and water bowls.",
    category: "PET_CARE",
    difficulty: "EASY",
    virtueFocus: ["RESPONSIBILITY", "STEWARDSHIP"],
    suggestedReward: { min: 5, max: 10 },
    suggestedChecklist: ["Refill food bowl", "Refill water bowl", "Wipe up any spills"],
  },
  {
    id: "sugg-003",
    ageRange: "5-7",
    title: "Sort Clean Laundry",
    description: "Sort folded laundry by family member.",
    category: "HOUSEHOLD",
    difficulty: "EASY",
    virtueFocus: ["DILIGENCE"],
    suggestedReward: { min: 5, max: 10 },
    suggestedChecklist: ["Make a pile for each person", "Stack neatly"],
  },
  // Ages 8-10
  {
    id: "sugg-004",
    ageRange: "8-10",
    title: "Clean Bathroom Counter",
    description: "Wipe down sink, counter, and mirror.",
    category: "HOUSEHOLD",
    difficulty: "MEDIUM",
    virtueFocus: ["DILIGENCE", "STEWARDSHIP"],
    suggestedReward: { min: 15, max: 25 },
    suggestedChecklist: ["Clear counter items", "Wipe sink with cleaner", "Wipe counter", "Clean mirror"],
  },
  {
    id: "sugg-005",
    ageRange: "8-10",
    title: "Pull Weeds",
    description: "Pull all visible weeds from one flower bed section.",
    category: "YARD_WORK",
    difficulty: "MEDIUM",
    virtueFocus: ["DILIGENCE"],
    suggestedReward: { min: 15, max: 30 },
    suggestedChecklist: ["Wear gloves", "Pull weeds at root", "Bag in yard waste"],
  },
  {
    id: "sugg-006",
    ageRange: "8-10",
    title: "Organize Bookshelf",
    description: "Sort books by category, then alphabetically.",
    category: "ORGANIZATION",
    difficulty: "MEDIUM",
    virtueFocus: ["RESPONSIBILITY", "FOLLOW_THROUGH"],
    suggestedReward: { min: 15, max: 25 },
    suggestedChecklist: ["Take all books off", "Sort by category", "Arrange alphabetically", "Dust shelves"],
  },
  // Ages 11-14
  {
    id: "sugg-007",
    ageRange: "11-14",
    title: "Wash the Car",
    description: "Wash exterior, vacuum interior, clean windows.",
    category: "OUTDOOR",
    difficulty: "HARD",
    virtueFocus: ["DILIGENCE", "STEWARDSHIP"],
    suggestedReward: { min: 30, max: 50 },
    suggestedChecklist: ["Rinse car", "Soap and scrub", "Rinse off soap", "Dry with towel", "Vacuum interior", "Clean windows"],
  },
  {
    id: "sugg-008",
    ageRange: "11-14",
    title: "Cook a Simple Meal",
    description: "Prepare dinner for the family — your choice of recipe.",
    category: "LEARNING",
    difficulty: "HARD",
    virtueFocus: ["INITIATIVE", "PROBLEM_SOLVING"],
    suggestedReward: { min: 30, max: 50 },
    suggestedChecklist: ["Plan menu", "Prep ingredients", "Cook safely", "Clean as you go"],
  },
  {
    id: "sugg-009",
    ageRange: "11-14",
    title: "Mow the Lawn",
    description: "Mow front and back yard with supervision.",
    category: "YARD_WORK",
    difficulty: "HARD",
    virtueFocus: ["DILIGENCE", "STEWARDSHIP"],
    suggestedReward: { min: 40, max: 60 },
    suggestedChecklist: ["Check oil/gas", "Mow front yard in straight lines", "Mow backyard", "Edge the sidewalk", "Put away mower"],
  },
  // Ages 15+
  {
    id: "sugg-010",
    ageRange: "15+",
    title: "Babysit Sibling",
    description: "Watch younger sibling for the evening.",
    category: "SERVICE",
    difficulty: "CHALLENGE",
    virtueFocus: ["RESPONSIBILITY", "SERVICE"],
    suggestedReward: { min: 60, max: 120 },
    suggestedChecklist: ["Plan activities", "Make dinner/snack", "Bedtime routine", "Tidy up after"],
  },
  {
    id: "sugg-011",
    ageRange: "15+",
    title: "Build a Project",
    description: "Pick a real project — a budget, a build, a plan — and complete it.",
    category: "BUSINESS",
    difficulty: "CHALLENGE",
    virtueFocus: ["INITIATIVE", "PROBLEM_SOLVING"],
    suggestedReward: { min: 75, max: 150 },
    suggestedChecklist: ["Define scope", "Plan steps", "Execute", "Document outcome"],
  },
  {
    id: "sugg-012",
    ageRange: "15+",
    title: "Manage Yard Section",
    description: "Take responsibility for one yard section all season.",
    category: "OUTDOOR",
    difficulty: "CHALLENGE",
    virtueFocus: ["STEWARDSHIP", "FOLLOW_THROUGH"],
    suggestedReward: { min: 100, max: 200 },
    suggestedChecklist: ["Plan upkeep schedule", "Maintain weekly", "Document progress"],
  },
];
