import type { Job } from "@/types";
import { DEMO_USERS, DEMO_CHILD_PROFILES } from "./users";

export const DEMO_JOBS: Job[] = [
  {
    id: "job-001",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-daniel",
    claimedBy: DEMO_USERS.daniel,
    assignedToId: "child-daniel",
    assignedTo: DEMO_CHILD_PROFILES.daniel,
    title: "Clean Your Room",
    description:
      "Pick up the floor, make your bed, organize your desk, and put dirty clothes in the hamper. Make it inspection-ready.",
    category: "HOUSEHOLD",
    difficulty: "MEDIUM",
    virtues: ["RESPONSIBILITY", "DILIGENCE"],
    tokenReward: 25,
    status: "SUBMITTED",
    dueDate: "2026-04-27T00:00:00Z",
    proofRequirement: "BEFORE_AND_AFTER",
    isRecurring: false,
    estimatedTime: "45 minutes",
    suggestedAgeRange: "11-14",
    checklist: [
      { id: "ck-001-1", text: "Make my bed", required: true, completed: true },
      { id: "ck-001-2", text: "Pick up all clothes", required: true, completed: true },
      { id: "ck-001-3", text: "Organize desk surface", required: true, completed: true },
      { id: "ck-001-4", text: "Vacuum the floor", required: true, completed: true },
      { id: "ck-001-5", text: "Dust shelves", required: false, completed: false },
      { id: "ck-001-6", text: "Upload after photo", required: true, completed: true },
    ],
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-04-25T14:30:00Z",
    beforePhoto: {
      id: "photo-001-before",
      invoiceId: "invoice-001",
      phase: "before",
      url: "/images/placeholder-before.jpg",
      isPlaceholder: true,
      uploadedAt: "2026-04-24T09:00:00Z",
    },
    afterPhoto: {
      id: "photo-001-after",
      invoiceId: "invoice-001",
      phase: "after",
      url: "/images/placeholder-after.jpg",
      isPlaceholder: true,
      uploadedAt: "2026-04-25T14:00:00Z",
    },
  },
  {
    id: "job-002",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    title: "Pull Weeds in the Front Yard",
    description:
      "Pull all visible weeds from the front flower bed. Fill one yard-waste bag. Wear gloves.",
    category: "YARD_WORK",
    difficulty: "HARD",
    virtues: ["DILIGENCE", "STEWARDSHIP"],
    tokenReward: 40,
    status: "OPEN",
    dueDate: "2026-04-30T00:00:00Z",
    proofRequirement: "BEFORE_AND_AFTER",
    isRecurring: false,
    createdAt: "2026-04-22T08:00:00Z",
    updatedAt: "2026-04-22T08:00:00Z",
  },
  {
    id: "job-003",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-mateo",
    claimedBy: DEMO_USERS.mateo,
    assignedToId: "child-mateo",
    assignedTo: DEMO_CHILD_PROFILES.mateo,
    title: "Organize the Bookshelf",
    description:
      "Sort all books by subject, then alphabetically. Put loose papers in the recycling bin. Dust the shelves when done.",
    category: "ORGANIZATION",
    difficulty: "MEDIUM",
    virtues: ["RESPONSIBILITY", "FOLLOW_THROUGH"],
    tokenReward: 20,
    status: "IN_PROGRESS",
    dueDate: "2026-04-28T00:00:00Z",
    proofRequirement: "AFTER_ONLY",
    isRecurring: false,
    createdAt: "2026-04-21T11:00:00Z",
    updatedAt: "2026-04-23T16:00:00Z",
  },
  {
    id: "job-004",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    title: "Wash the Car Mats",
    description:
      "Take out all four car mats, scrub them with the brush and soapy water, rinse, and leave to dry in the driveway.",
    category: "HOUSEHOLD",
    difficulty: "MEDIUM",
    virtues: ["DILIGENCE", "STEWARDSHIP"],
    tokenReward: 15,
    status: "OPEN",
    proofRequirement: "AFTER_ONLY",
    isRecurring: false,
    createdAt: "2026-04-23T09:00:00Z",
    updatedAt: "2026-04-23T09:00:00Z",
  },
  {
    id: "job-005",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-daniel",
    claimedBy: DEMO_USERS.daniel,
    assignedToId: "child-daniel",
    assignedTo: DEMO_CHILD_PROFILES.daniel,
    title: "Read to Your Younger Brother",
    description:
      "Read two chapters from Mateo's current chapter book with him. Use different voices for characters. Make it fun!",
    category: "SERVICE",
    difficulty: "EASY",
    virtues: ["SERVICE", "COMMUNICATION"],
    tokenReward: 15,
    status: "APPROVED",
    dueDate: "2026-04-20T00:00:00Z",
    proofRequirement: "NONE",
    isRecurring: false,
    createdAt: "2026-04-18T10:00:00Z",
    updatedAt: "2026-04-19T18:00:00Z",
  },
  {
    id: "job-006",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    title: "Create a Lemonade Stand Budget",
    description:
      "Write out a simple business plan for a lemonade stand: list costs (lemons, sugar, cups, signs), estimate sales price per cup, and figure out how many cups you need to sell to break even.",
    category: "BUSINESS",
    difficulty: "CHALLENGE",
    virtues: ["INITIATIVE", "PROBLEM_SOLVING", "STEWARDSHIP"],
    tokenReward: 50,
    status: "OPEN",
    proofRequirement: "AFTER_ONLY",
    isRecurring: false,
    createdAt: "2026-04-24T09:00:00Z",
    updatedAt: "2026-04-24T09:00:00Z",
  },
  {
    id: "job-007",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-mateo",
    claimedBy: DEMO_USERS.mateo,
    assignedToId: "child-mateo",
    assignedTo: DEMO_CHILD_PROFILES.mateo,
    title: "Take Out Trash for the Week",
    description:
      "Every Monday and Thursday: take trash cans to curb by 7am. Bring them back in by evening. Roll them to the side of the house when done.",
    category: "HOUSEHOLD",
    difficulty: "EASY",
    virtues: ["RESPONSIBILITY", "FOLLOW_THROUGH"],
    tokenReward: 20,
    status: "CLAIMED",
    proofRequirement: "NONE",
    isRecurring: true,
    createdAt: "2026-04-15T00:00:00Z",
    updatedAt: "2026-04-22T08:00:00Z",
  },
  {
    id: "job-008",
    familyId: "family-reyes",
    postedById: "user-joe",
    postedBy: DEMO_USERS.joe,
    title: "Organize the Pantry Shelf",
    description:
      "Grandpa Joe says: Take everything off the bottom pantry shelf, wipe it down, then organize it by category — canned goods together, snacks together, baking things together. You know what goes where!",
    category: "ORGANIZATION",
    difficulty: "MEDIUM",
    virtues: ["RESPONSIBILITY", "DILIGENCE"],
    tokenReward: 30,
    status: "OPEN",
    proofRequirement: "BEFORE_AND_AFTER",
    isRecurring: false,
    createdAt: "2026-04-25T11:00:00Z",
    updatedAt: "2026-04-25T11:00:00Z",
  },
];
