import type { Job } from "@/types";
import { DEMO_USERS, DEMO_CHILD_PROFILES } from "./users";

export const DEMO_JOBS: Job[] = [
  {
    id: "job-001",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-daniel",
    claimedBy: DEMO_USERS.daniel,
    assignedToId: "child-daniel",
    assignedTo: DEMO_CHILD_PROFILES.daniel,
    title: "Practice Saying Hi First",
    description:
      "Say hi first to 10 people today, look them in the eye, and use their name if you know it. Write one sentence about what you noticed.",
    category: "HOUSEHOLD",
    difficulty: "MEDIUM",
    virtues: ["COMMUNICATION", "RESILIENCE"],
    tokenReward: 20,
    status: "SUBMITTED",
    dueDate: "2026-04-27T00:00:00Z",
    proofRequirement: "BEFORE_AND_AFTER",
    isRecurring: false,
    estimatedTime: "1 day",
    suggestedAgeRange: "11-14",
    checklist: [
      { id: "ck-001-1", text: "Say hi first to 10 people", required: true, completed: true },
      { id: "ck-001-2", text: "Look people in the eye", required: true, completed: true },
      { id: "ck-001-3", text: "Use their name if you know it", required: true, completed: true },
      { id: "ck-001-4", text: "Write one reflection sentence", required: true, completed: true },
      { id: "ck-001-5", text: "Ask one follow-up question", required: false, completed: false },
      { id: "ck-001-6", text: "Tell Mom or Dad when finished", required: true, completed: true },
    ],
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-04-25T14:30:00Z",
    beforePhoto: {
      id: "photo-001-before",
      invoiceId: "invoice-001",
      phase: "before",
      url: "/images/placeholder-before.jpg",
      isPlaceholder: true,
      uploadedAt: "2026-04-24T09:00:00Z",
    },
    afterPhoto: {
      id: "photo-001-after",
      invoiceId: "invoice-001",
      phase: "after",
      url: "/images/placeholder-after.jpg",
      isPlaceholder: true,
      uploadedAt: "2026-04-25T14:00:00Z",
    },
  },
  {
    id: "job-002",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    title: "Help Restore the Front Yard",
    description:
      "Restore the front flower bed by pulling visible weeds, filling one yard-waste bag, and leaving the entryway more welcoming for the family.",
    category: "YARD_WORK",
    difficulty: "HARD",
    virtues: ["DILIGENCE", "STEWARDSHIP"],
    tokenReward: 40,
    status: "OPEN",
    dueDate: "2026-04-30T00:00:00Z",
    proofRequirement: "BEFORE_AND_AFTER",
    isRecurring: false,
    createdAt: "2026-04-22T08:00:00Z",
    updatedAt: "2026-04-22T08:00:00Z",
  },
  {
    id: "job-003",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-mateo",
    claimedBy: DEMO_USERS.mateo,
    assignedToId: "child-mateo",
    assignedTo: DEMO_CHILD_PROFILES.mateo,
    title: "Create a Peaceful Reading Shelf",
    description:
      "Make the bookshelf easier for everyone to use: sort by subject, recycle loose papers, dust the shelves, and leave a small note showing where things belong.",
    category: "ORGANIZATION",
    difficulty: "MEDIUM",
    virtues: ["RESPONSIBILITY", "FOLLOW_THROUGH"],
    tokenReward: 20,
    status: "IN_PROGRESS",
    dueDate: "2026-04-28T00:00:00Z",
    proofRequirement: "AFTER_ONLY",
    isRecurring: false,
    createdAt: "2026-04-21T11:00:00Z",
    updatedAt: "2026-04-23T16:00:00Z",
  },
  {
    id: "job-004",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    title: "Serve the Family Car",
    description:
      "Take out all four car mats, scrub them with care, rinse, and leave them to dry so the next family drive feels cleaner and calmer.",
    category: "HOUSEHOLD",
    difficulty: "MEDIUM",
    virtues: ["DILIGENCE", "STEWARDSHIP"],
    tokenReward: 15,
    status: "OPEN",
    proofRequirement: "AFTER_ONLY",
    isRecurring: false,
    createdAt: "2026-04-23T09:00:00Z",
    updatedAt: "2026-04-23T09:00:00Z",
  },
  {
    id: "job-005",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-daniel",
    claimedBy: DEMO_USERS.daniel,
    assignedToId: "child-daniel",
    assignedTo: DEMO_CHILD_PROFILES.daniel,
    title: "Do a Favor for Your Younger Brother",
    description:
      "Ask Mateo what would help him today, then do one useful favor with a cheerful attitude. If he picks reading together, make it fun.",
    category: "SERVICE",
    difficulty: "EASY",
    virtues: ["SERVICE", "COMMUNICATION"],
    tokenReward: 15,
    status: "APPROVED",
    dueDate: "2026-04-20T00:00:00Z",
    proofRequirement: "NONE",
    isRecurring: false,
    createdAt: "2026-04-18T10:00:00Z",
    updatedAt: "2026-04-19T18:00:00Z",
  },
  {
    id: "job-006",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    title: "Design a Value-Creation Plan",
    description:
      "Write a simple plan for creating value without trading hours for dollars: choose a problem, list costs, decide a price, and explain how it helps people.",
    category: "BUSINESS",
    difficulty: "CHALLENGE",
    virtues: ["INITIATIVE", "PROBLEM_SOLVING", "STEWARDSHIP"],
    tokenReward: 50,
    status: "OPEN",
    proofRequirement: "AFTER_ONLY",
    isRecurring: false,
    createdAt: "2026-04-24T09:00:00Z",
    updatedAt: "2026-04-24T09:00:00Z",
  },
  {
    id: "job-007",
    familyId: "family-reyes",
    postedById: "user-santiago",
    postedBy: DEMO_USERS.santiago,
    claimedById: "user-mateo",
    claimedBy: DEMO_USERS.mateo,
    assignedToId: "child-mateo",
    assignedTo: DEMO_CHILD_PROFILES.mateo,
    title: "Own Trash Day Without Reminders",
    description:
      "Every Monday and Thursday: get the trash cans to the curb on time and bring them back without reminders. This is follow-through training.",
    category: "HOUSEHOLD",
    difficulty: "EASY",
    virtues: ["RESPONSIBILITY", "FOLLOW_THROUGH"],
    tokenReward: 20,
    status: "CLAIMED",
    proofRequirement: "NONE",
    isRecurring: true,
    createdAt: "2026-04-15T00:00:00Z",
    updatedAt: "2026-04-22T08:00:00Z",
  },
  {
    id: "job-008",
    familyId: "family-reyes",
    postedById: "user-joe",
    postedBy: DEMO_USERS.joe,
    title: "Create a Welcoming Pantry Shelf",
    description:
      "Grandpa Joe says: take everything off the bottom pantry shelf, wipe it down, then organize it by category so the family can find what it needs quickly.",
    category: "ORGANIZATION",
    difficulty: "MEDIUM",
    virtues: ["COMMUNICATION", "RESILIENCE"],
    tokenReward: 30,
    status: "OPEN",
    proofRequirement: "BEFORE_AND_AFTER",
    isRecurring: false,
    createdAt: "2026-04-25T11:00:00Z",
    updatedAt: "2026-04-25T11:00:00Z",
  },
];
