import type { Reward, RewardRedemption } from "@/types";
import { DEMO_CHILD_PROFILES } from "./users";

export const DEMO_REWARDS: Reward[] = [
  {
    id: "reward-001",
    familyId: "family-reyes",
    title: "Extra Dessert",
    description: "Choose any dessert after dinner tonight.",
    tokenCost: 30,
    type: "CUSTOM",
    isActive: true,
    emoji: "🍪",
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "reward-002",
    familyId: "family-reyes",
    title: "Movie Night",
    description: "Pick any movie and we'll watch it together as a family.",
    tokenCost: 50,
    type: "ACTIVITY",
    isActive: true,
    emoji: "🎬",
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "reward-003",
    familyId: "family-reyes",
    title: "30 Min Extra Screen Time",
    description: "One-time screen time bonus — any device, any day this week.",
    tokenCost: 75,
    type: "SCREEN_TIME",
    isActive: true,
    emoji: "📱",
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "reward-004",
    familyId: "family-reyes",
    title: "Ice Cream Trip",
    description: "Trip to your favorite ice cream shop — your choice of flavor.",
    tokenCost: 100,
    type: "ACTIVITY",
    isActive: true,
    emoji: "🍦",
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "reward-005",
    familyId: "family-reyes",
    title: "New Book",
    description: "Pick any book up to $15 from the bookstore or Amazon.",
    tokenCost: 100,
    type: "CUSTOM",
    isActive: true,
    emoji: "📖",
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "reward-006",
    familyId: "family-reyes",
    title: "Choose Family Dinner",
    description: "Pick what we're having for dinner — restaurant or homemade.",
    tokenCost: 150,
    type: "ACTIVITY",
    isActive: true,
    emoji: "🍕",
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "reward-007",
    familyId: "family-reyes",
    title: "Stay Up 30 Min Later",
    description: "One night of your choice — 30 extra minutes past bedtime.",
    tokenCost: 200,
    type: "CUSTOM",
    isActive: true,
    emoji: "🌙",
    createdAt: "2024-09-01T00:00:00Z",
  },
];

export const DEMO_REDEMPTIONS: RewardRedemption[] = [
  {
    id: "redemption-001",
    rewardId: "reward-002",
    reward: DEMO_REWARDS[1],
    childId: "child-daniel",
    child: DEMO_CHILD_PROFILES.daniel,
    status: "APPROVED",
    requestedAt: "2026-04-10T15:00:00Z",
    resolvedAt: "2026-04-10T18:00:00Z",
  },
  {
    id: "redemption-002",
    rewardId: "reward-001",
    reward: DEMO_REWARDS[0],
    childId: "child-mateo",
    child: DEMO_CHILD_PROFILES.mateo,
    status: "APPROVED",
    requestedAt: "2026-04-22T14:00:00Z",
    resolvedAt: "2026-04-22T19:00:00Z",
  },
];
