import type { WalletTransaction } from "@/types";

export const DEMO_TRANSACTIONS: WalletTransaction[] = [
  {
    id: "tx-001",
    childId: "child-daniel",
    type: "EARNED",
    tokens: 20,
    description: "Completed: Take out trash for the week",
    jobId: "job-007",
    createdAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "tx-002",
    childId: "child-daniel",
    type: "EARNED",
    tokens: 15,
    description: "Completed: Read to your younger brother",
    jobId: "job-005",
    createdAt: "2026-04-19T18:00:00Z",
  },
  {
    id: "tx-003",
    childId: "child-daniel",
    type: "BONUS",
    tokens: 5,
    description: "Bonus: Went above and beyond reading to Mateo",
    invoiceId: "invoice-002",
    createdAt: "2026-04-19T18:05:00Z",
  },
  {
    id: "tx-004",
    childId: "child-daniel",
    type: "REDEEMED",
    tokens: -50,
    description: "Redeemed: Movie night",
    createdAt: "2026-04-10T18:00:00Z",
  },
  {
    id: "tx-005",
    childId: "child-daniel",
    type: "EARNED",
    tokens: 30,
    description: "Completed: Organize Dad's Garage Shelf",
    jobId: "job-009",
    createdAt: "2026-04-05T16:00:00Z",
  },
  {
    id: "tx-006",
    childId: "child-mateo",
    type: "EARNED",
    tokens: 20,
    description: "Completed: Take out trash for the week",
    jobId: "job-007",
    createdAt: "2026-04-20T09:00:00Z",
  },
  {
    id: "tx-007",
    childId: "child-mateo",
    type: "REDEEMED",
    tokens: -30,
    description: "Redeemed: Extra dessert",
    createdAt: "2026-04-22T19:00:00Z",
  },
  {
    id: "tx-008",
    childId: "child-mateo",
    type: "EARNED",
    tokens: 15,
    description: "Completed: Water the plants",
    createdAt: "2026-04-12T11:00:00Z",
  },
];
